feat: Add a RPC reference for transaction on the XRPL.
TowoLabs/walletconnect-docs pull request #1
Opened 2023-02-28 10:28 UTC by antondalgren

2023-02-28 11:08 UTC, RareData requested changes
We should add both of these from the get go:

- `xrpl_signSubmitTransaction` alt. `xrpl_sendTransaction` (signed and submitted to an XRPL node)
- `xrpl_signTransaction` (signed and _ready_ to be submitted to an XRPL node)

2023-02-28 14:37 UTC, RareData commented on docs/advanced/rpc-reference/xrpl-rpc.md
> +This method is used to sign a transaction to later be submitted to the XRPL. The basis of a transaction is defined by the [XRPL Transaction Common Fields][], it defines the properties that are availa
Is is our words or found in reference documentation that tickets is strongly recommended? It's a rather advanced feature.

2023-02-28 14:40 UTC, RareData commented on docs/advanced/rpc-reference/xrpl-rpc.md
> +        "tx_blob": "120000240000000461D4838D7EA4C6800000000000000000000000000055534400000000004B4E9C06F24296074F7BC48F92A97916C6DC5EA968400000000000000F732103AB40A0490F9B7ED8DF29D246BF2D6269820A0EE77
Why is this encoded in the xrpl binary codec, but not the previous response?

2023-02-28 14:42 UTC, antondalgren commented on docs/advanced/rpc-reference/xrpl-rpc.md
> +This method is used to sign a transaction to later be submitted to the XRPL. The basis of a transaction is defined by the [XRPL Transaction Common Fields][], it defines the properties that are availa
It's not found in the reference documentation.

2023-02-28 15:10 UTC, RareData commented on docs/advanced/rpc-reference/xrpl-rpc.md
> +        "tx_blob": "120000240000000461D4838D7EA4C6800000000000000000000000000055534400000000004B4E9C06F24296074F7BC48F92A97916C6DC5EA968400000000000000F732103AB40A0490F9B7ED8DF29D246BF2D6269820A0EE77
I think it makes more sense to always send/receive JSON to not require the dapp or wallet to know about XRPL binary codecs. If a dapp wants to do special logic, multi-signing or delayed submission, only those dapps then need to encoding before submitting to a node.

2023-02-28 15:20 UTC, RareData commented on docs/advanced/rpc-reference/xrpl-rpc.md
> +{
We may want to place the TX JSON inside it's own object, to allow for extensibility. Like flagging that no fields should be auto-filled by the wallet.

```
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "xrpl_sendTransaction",
    "params": {
            "offline": false,
            "tx_json": {
                "Account": "rf1BiGeXwwQoi8Z2ueFYTEXSwuJYfV2Jpn",
                "Amount": {
                    "currency": "USD",
                    "issuer": "rf1BiGeXwwQoi8Z2ueFYTEXSwuJYfV2Jpn",
                    "value": "1"
                },
                "Destination": "ra5nK24KXen9AHvsdFTKHSANinZseWnPcX",
                "TransactionType": "Payment"
            }
        }
    }
}
```

If we submit a transaction, we want to return the status and we may as well return both an optional binary version and the JSON equivalent.
```
// Result
{
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "status": "success",
        "tx_blob": "1200002280000000240000016861D4838D7EA4C6800000000000000000000000000055534400000000004B4E9C06F24296074F7BC48F92A97916C6DC5EA9684000000000002710732103AB40A0490F9B7ED8DF29D246BF2D6269820A0EE7742ACDD457BEA7C7D0931EDB7446304402200E5C2DD81FDF0BE9AB2A8D797885ED49E804DBF28E806604D878756410CA98B102203349581946B0DDA06B36B35DBC20EDA27552C1F167BCF5C6ECFF49C6A46F858081144B4E9C06F24296074F7BC48F92A97916C6DC5EA983143E9D4A2B8AA0780F682D136F7A56D6724EF53754",
        "tx_json": {
            "Account": "rf1BiGeXwwQoi8Z2ueFYTEXSwuJYfV2Jpn",
            "Amount": {
               "currency": "USD",
               "issuer": "rf1BiGeXwwQoi8Z2ueFYTEXSwuJYfV2Jpn",
               "value": "1"
            },
            "Destination": "ra5nK24KXen9AHvsdFTKHSANinZseWnPcX",
            "Fee": "10000",
            "Flags": 2147483648,
            "Sequence": 360,
            "SigningPubKey": "03AB40A0490F9B7ED8DF29D246BF2D6269820A0EE7742ACDD457BEA7C7D0931EDB",
            "TransactionType": "Payment",
            "TxnSignature": "304402200E5C2DD81FDF0BE9AB2A8D797885ED49E804DBF28E806604D878756410CA98B102203349581946B0DDA06B36B35DBC20EDA27552C1F167BCF5C6ECFF49C6A46F8580",
            "hash": "4D5D90890F8D49519E4151938601EF3D0B30B16CD6A519D9C99102C9FA77F7E0"
        }
    }
}
```

2023-02-28 15:23 UTC, RareData commented on docs/advanced/rpc-reference/xrpl-rpc.md
> +    "method": "xrpl_sendTransaction",
xrpl_signTransaction

2023-02-28 15:24 UTC, RareData commented on docs/advanced/rpc-reference/xrpl-rpc.md
> +        "tx_blob": "120000240000000461D4838D7EA4C6800000000000000000000000000055534400000000004B4E9C06F24296074F7BC48F92A97916C6DC5EA968400000000000000F732103AB40A0490F9B7ED8DF29D246BF2D6269820A0EE77
Or as in the [previous comment](https://github.com/TowoLabs/walletconnect-docs/pull/1/files#r1120242747), have the wallet optionally return an encoded version (ready to be submitted)

2023-02-28 15:39 UTC, RareData requested changes
Comments made on specific methods mostly reference the way xrpld handles unsigned, signed and submitted TXs.

See e.g:
https://xrpl.org/sign.html
https://xrpl.org/sign_for.html

We have a two options. We could:
1. Mimic this behaviour and do xrpl_signTransaction and xrpl_signTransactionFor with a flag that indicates if it should be submitted or not.
2. Use specific methods xrpl_signTransaction and xrpl_sendTransaction that instead can be extended with the `account` and `offline` fields to flag who'll be the signer and if fields can be autofilled.

2023-02-28 15:39 UTC, RareData commented on docs/advanced/rpc-reference/xrpl-rpc.md
> +        "tx_blob": "120000240000000461D4838D7EA4C6800000000000000000000000000055534400000000004B4E9C06F24296074F7BC48F92A97916C6DC5EA968400000000000000F732103AB40A0490F9B7ED8DF29D246BF2D6269820A0EE77
Since XRPL supports regular keys and multi-signing, we need to be able to say what account should sign the transaction and flag that it's multi-signing with an empty SigningPubKey (again, same method as used by xrpld).
```
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "xrpl_signTransaction",
    "params": {
        "account": "rLFd1FzHMScFhLsXeaxStzv3UC97QHGAbM",
        "tx_json": {
            "TransactionType": "TrustSet",
            "Account": "rEuLyBCvcw4CFmzv8RepSiAoNgF8tTGJQC",
            "Flags": 262144,
            "LimitAmount": {
                "currency": "USD",
                "issuer": "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh",
                "value": "100"
            },
            "Sequence": 2,
            "SigningPubKey": "",
            "Fee": "30000"
        }
    }
}
```

For the response, we again do it as both a tx_blob, tx_json and skip the status indicating that it has not been submitted.
```
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "tx_blob": "1200142200040000240000000263D5038D7EA4C680000000000000000000000000005553440000000000B5F762798A53D543A014CAF8B297CFF8F2F937E868400000000000753073008114A3780F5CB5A44D366520FC44055E8ED44D9A2270F3E0107321EDDF4ECB8F34A168143B928D48EFE625501FB8552403BBBD3FC038A5788951D7707440C3DCA3FEDE6D785398EEAB10A46B44047FF1B0863FC4313051FB292C991D1E3A9878FABB301128FE4F86F3D8BE4706D53FA97F5536DBD31AF14CD83A5ACDEB068114D96CB910955AB40A0E987EEE82BB3CEDD4441AAAE1F1",
    "tx_json": {
      "Account": "rEuLyBCvcw4CFmzv8RepSiAoNgF8tTGJQC",
      "Fee": "30000",
      "Flags": 262144,
      "LimitAmount": {
        "currency": "USD",
        "issuer": "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh",
        "value": "100"
      },
      "Sequence": 2,
      "Signers": [
        {
          "Signer": {
            "Account": "rLFd1FzHMScFhLsXeaxStzv3UC97QHGAbM",
            "SigningPubKey": "EDDF4ECB8F34A168143B928D48EFE625501FB8552403BBBD3FC038A5788951D770",
            "TxnSignature": "C3DCA3FEDE6D785398EEAB10A46B44047FF1B0863FC4313051FB292C991D1E3A9878FABB301128FE4F86F3D8BE4706D53FA97F5536DBD31AF14CD83A5ACDEB06"
          }
        }
      ],
      "SigningPubKey": "",
      "TransactionType": "TrustSet",
      "hash": "5216A13A3E3CF662352F0B430C7D82B7450415B6883DD428B5EC1DF1DE45DD8C"
    }
  }
}
```

2023-02-28 15:39 UTC, RareData commented on docs/advanced/rpc-reference/xrpl-rpc.md
> +This method is used to sign a transaction to later be submitted to the XRPL. The basis of a transaction is defined by the [XRPL Transaction Common Fields][], it defines the properties that are availa
Then I'd say we should avoid using any reference to tickets and just possibly mention the three different ways of signing, as master key, regular key or multi-signer. An option mostly used for multi-signing is to pre-book a specific sequence number using a ticket, but it's not recommended or necessary, it's a niche thing.

2023-03-02 13:52 UTC, patriksletmo commented on docs/advanced/rpc-reference/xrpl-rpc.md
> +This method is used to sign and send a transaction to the XRP Ledger. The basis of a transaction is defined by the [XRPL Transaction Common Fields][], it defines the properties that are available to
> The basis of a transaction is defined by the [XRPL Transaction Common Fields][], it defines the properties that are available to all transaction types. The actual transactions that are supported on the XRPL can be found [here][XRPL Transaction Types]. It is expected that the parameters that are defined as `Required`, but not `auto-fillable` are provided by the dapp to the wallet.'

This part is similar between the two methods. Can we define it in its own section to avoid repeating ourselves here?

2023-03-02 13:52 UTC, patriksletmo commented on docs/advanced/rpc-reference/xrpl-rpc.md
> +        "tx_blob": "120000240000000461D4838D7EA4C6800000000000000000000000000055534400000000004B4E9C06F24296074F7BC48F92A97916C6DC5EA968400000000000000F732103AB40A0490F9B7ED8DF29D246BF2D6269820A0EE77
I agree with the above.

2023-03-02 14:58 UTC, RareData commented
What is your opinion on using `xrpl_sendTransaction` and `xrpl_signTransaction`? They do the same thing with the only difference being TX submission. If we want to separate multisig. and regular key TXs (not all wallets may support it), we'd also get `xrpl_sendTransactionFor` and `xrpl_signTransactionFor`.

I'd opt for `xrpl_signTransaction` and `xrpl_signTransactionFor` with a property to control submission, `submit: true|false`

2023-03-23 08:21 UTC, tadejgolobic commented on docs/advanced/rpc-reference/xrpl-rpc.md
> +{
I know that this is exactly what rippled is expecting, but could we make Account field optional? For example, you can generate transaction, and then down the line maybe user can select with what account he wants to sign the transaction?

This would work exactly the same way also as XUMM works: https://xumm.readme.io/docs/your-first-payload

> You can however leave out the fields that are client (signer) specific, like in this example (Payment) the "Account"-field, as the xumm app running on the device of the end user will fill that field based on the selected account used to sign.

2023-03-27 09:25 UTC, tadejgolobic commented on docs/advanced/rpc-reference/xrpl-rpc.md
> +This method is used to sign and send a transaction to the XRP Ledger. The basis of a transaction is defined by the [XRPL Transaction Common Fields][], it defines the properties that are available to
of course, this can be done also on method for signing transaction
```
{
"id": 1,
    "jsonrpc": "2.0",
    "method": "xrpl_signTransaction",
    "params": {
        "submit": true
        "tx_json": {
            ...
        }
}
```

2023-04-19 17:34 UTC, RareData commented on docs/advanced/rpc-reference/xrpl-rpc.md
> +This method is used to sign and send a transaction to the XRP Ledger. The basis of a transaction is defined by the [XRPL Transaction Common Fields][], it defines the properties that are available to
The default case for interacting with a wallet over WalletConnect is to have it sign and submit something, so we suggest using an optional parameter `submit: false` (default true). We want to minimize the number of different methods. The minimum case would be one method for single-signing and one method for multi-signing.

2023-04-19 17:40 UTC, RareData commented on docs/advanced/rpc-reference/xrpl-rpc.md
> +This method is used to sign and send a transaction to the XRP Ledger. The basis of a transaction is defined by the [XRPL Transaction Common Fields][], it defines the properties that are available to
We want all dapps to be able to use just JSON and not be aware of ripple binary codec or similar, so we'd opt for making `tx_json` required and `tx_blob` optional.

2023-04-21 11:27 UTC, merged